# Default values for atvt-saas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev
namespace: stringer-management
# TODO: Add Support for Dynamic registry.
imagePullSecret: stringer
replicaCount: 1
infra:
  istio:
    enabled: False
  vrli:
    enabled: False
prometheus:
  scrape: true
  path: /actuator/prometheus
  port: 8081

authService:
  name: stringer-auth
  appLabel: stringer-auth
  replicas: 1
  image: 
    repository: <REPO>
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
